service: group1-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  postHandler:
    handler: handler.postHandler
    events:
      - httpApi:
          path: /post-endpoint
          method: post

  sqsHandler:
    handler: handler.sqsHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - group1SQSQueue
              - Arn
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures

resources:
  Resources:
    group1SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: group1-sqs-queue

plugins:
  - serverless-offline
