service: my-service

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  snsHandler:
    handler: handler.snsHandler
    events:
      - sns: my-sns-topic
        arn:
          Fn::GetAtt: [SNSTopic, Arn]

  httpHandler:
    handler: handler.httpHandler
    events:
      - httpApi:
          path: /hello
          method: get

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: my-sns-topic

plugins:
  - serverless-offline
