service: grp1-sqs-lambda

provider:
  name: aws
  runtime: nodejs18.x  # Updated to Node.js 18.x
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt:
            - MessageQueue
            - Arn

functions:
  sendToSQS:
    handler: handler.sendMessage
    environment:
      SQS_QUEUE_URL:
        Ref: grp1MessageQueue
    events:
      - http:
          path: send
          method: post

resources:
  Resources:
    grp1MessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: grp1Queue

  Outputs:
    SQSQueueUrl:
      Value:
        Ref: grp1MessageQueue





# service: grp1-service
# frameworkVersion: '3'

# provider:
#   name: aws
#   runtime: nodejs20.x
#   region: ap-southeast-1

# functions:
#   postHandler:
#     handler: handler.postHandler
#     events:
#       - httpApi:
#           path: /post-endpoint
#           method: post

#   sqsHandler:
#     handler: handler.sqsHandler
#     events:
#       - sqs:
#           arn:
#             Fn::GetAtt:
#               - grp1SQSQueue
#               - Arn
#           batchSize: 10
#           maximumBatchingWindow: 60
#           functionResponseType: ReportBatchItemFailures

# resources:
#   Resources:
#     grp1SQSQueue:
#       Type: AWS::SQS::Queue
#       Properties:
#         QueueName: grp1-sqs-queue

# plugins:
#   - serverless-offline
