# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: skillsunionsaravanan
service: my-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  snsHandler:
    handler: handler.snsHandler
    events:
      - sns: group1-sns-topic
        arn:
          Fn::GetAtt: [SNSTopic, Arn]

  httpHandler:
    handler: handler.httpHandler
    events:
      - httpApi:
          path: /hello
          method: get

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: group1-sns-topic

plugins:
  - serverless-offline
