name: Serverless CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Define the Node.js version

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies (Serverless and plugins)
      - name: Install dependencies
        run: npm ci

      # Step 4: Configure AWS credentials (ensure that AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set in GitHub Secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # Step 5: Deploy the Serverless application
      - name: Deploy with Serverless
        run: npx serverless deploy --stage production

      # Step 6: Post-deployment verification (Optional)
      - name: Post-deployment test
        run: curl -I https://your-api-url.com/hello  # Replace with your actual API endpoint

